//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtractorSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtractorSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap addFile {
            get {
                object obj = ResourceManager.GetObject("addFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon aww {
            get {
                object obj = ResourceManager.GetObject("aww", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;Name&quot;: &quot;中文(简体)&quot;,
        ///  &quot;LCID&quot;: 2052,
        ///  &quot;Group&quot;: {
        ///    &quot;Dictionary&quot;: {
        ///      &quot;Apply&quot;: &quot;应用&quot;,
        ///      &quot;OK&quot;: &quot;确定&quot;,
        ///      &quot;Cancel&quot;: &quot;取消&quot;,
        ///      &quot;GamePath&quot;: &quot;游戏路径&quot;,
        ///      &quot;Browse&quot;: &quot;浏览&quot;,
        ///      &quot;HandleObject&quot;: &quot;处理对象&quot;,
        ///      &quot;HandleContent&quot;: &quot;处理内容&quot;,
        ///      &quot;HandleImg&quot;: &quot;Img处理&quot;,
        ///      &quot;HandleImage&quot;: &quot;贴图处理&quot;,
        ///      &quot;CheckImg&quot;: &quot;当前所选Img&quot;,
        ///      &quot;AllImg&quot;: &quot;所有Img&quot;,
        ///      &quot;CheckImage&quot;: &quot;当前所选贴图&quot;,
        ///      &quot;AllImage&quot;: &quot;所有贴图&quot;,
        ///      &quot;ImageResources&quot;: &quot;图片资源&quot;,
        ///      &quot;SoundResources&quot;: &quot;音效资源&quot;,
        ///      &quot;Width&quot;: &quot;宽&quot;,        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap classify {
            get {
                object obj = ResourceManager.GetObject("classify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;UserConfig&quot;: &quot;conf.json&quot;,
        ///
        ///  &quot;FlashSpeed&quot;: 20,
        ///
        ///  &quot;GamePath&quot;: &quot;&quot;,
        ///
        ///  &quot;SaveImagePath&quot;: &quot;&quot;,
        ///
        ///  &quot;SaveImageTip&quot;: true,
        ///
        ///  &quot;Version&quot;: &quot;1.6.0.1&quot;,
        ///
        ///  &quot;GridGap&quot;: 100,
        ///
        ///  &quot;AutoSave&quot;: false,
        ///
        ///  &quot;LineLevel&quot;: 0.5,
        ///
        ///  &quot;LCID&quot;: 2052,
        ///
        ///  &quot;SaveImageAllPath&quot;: false,
        ///
        ///  &quot;LayerMaximum&quot;: 20,
        ///
        ///
        ///
        ///  &quot;UpdateUrl&quot;: &quot;http://extractorsharp.kritsu.net/api/program/update&quot;,
        ///
        ///  &quot;UpdateExeUrl&quot;: &quot;http://static.kritsu.net/install.exe&quot;,
        ///
        ///  &quot;DebugUrl&quot;: &quot;http://extractorsharp.kritsu.net/api/feedback/post&quot;,
        ///
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap feedback {
            get {
                object obj = ResourceManager.GetObject("feedback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap gif {
            get {
                object obj = ResourceManager.GetObject("gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap grid {
            get {
                object obj = ResourceManager.GetObject("grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap link {
            get {
                object obj = ResourceManager.GetObject("link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap newFile {
            get {
                object obj = ResourceManager.GetObject("newFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position {
            get {
                object obj = ResourceManager.GetObject("position", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	Name:&quot;default&quot;,
        ///	Rules:{
        ///	  &apos;body&apos;: 0
        ///	  &apos;bodyh&apos;: 0
        ///	  &apos;bgloveb&apos;: 650
        ///	  &apos;bglovea&apos;: 2150
        ///	  &apos;bglovec&apos;: 2790
        ///	  &apos;revc&apos;: 2790
        ///	  &apos;bglovex&apos;: 1350
        ///	  &apos;revb&apos;: 650
        ///	  &apos;gauntletx&apos;: 1350
        ///	  &apos;clawc&apos;: 2790
        ///	  &apos;clawb&apos;: 650
        ///	  &apos;clawa&apos;: 2150
        ///	  &apos;shoesb&apos;: 1200
        ///	  &apos;shoesc&apos;: 1600
        ///	  &apos;shoesa&apos;: 1400
        ///	  &apos;shoesf&apos;: 2880
        ///	  &apos;shoesg&apos;: 1450
        ///	  &apos;gauntletb&apos;: 650
        ///	  &apos;gauntletc&apos;: 2790
        ///	  &apos;gauntleta&apos;: 2150
        ///	  &apos;clawx&apos;: 1350
        ///	  &apos;sswdc&apos;: 4200
        ///	  &apos;boneclawb&apos;: 650
        ///	  &apos;boneclawa&apos;: 2150
        ///	  &apos;sswdb&apos;: 650
        ///	  &apos;faceg [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap record {
            get {
                object obj = ResourceManager.GetObject("record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap repair {
            get {
                object obj = ResourceManager.GetObject("repair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap replace {
            get {
                object obj = ResourceManager.GetObject("replace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ruler {
            get {
                object obj = ResourceManager.GetObject("ruler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap saveAs {
            get {
                object obj = ResourceManager.GetObject("saveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sort {
            get {
                object obj = ResourceManager.GetObject("sort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] success {
            get {
                object obj = ResourceManager.GetObject("success", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///  {
        ///    &quot;Version&quot;: &quot;1.0.0.1&quot;,
        ///    &quot;Info&quot;: [
        ///      &quot;优化试衣间,新增魔枪士&quot;
        ///    ]
        ///  },
        ///  {
        ///    &quot;Version&quot;: &quot;1.0.1.0&quot;,
        ///    &quot;Info&quot;: [
        ///      &quot;优化动画播放功能,修复内存溢出bug&quot;,
        ///      &quot;反Ex加密,防止因为Ex加密导致路径错误&quot;
        ///    ]
        ///  },
        ///  {
        ///    &quot;Version&quot;: &quot;1.0.2.0&quot;,
        ///    &quot;Time&quot;: &quot;2017年5月12日13:42:32&quot;,
        ///    &quot;Info&quot;: [
        ///      &quot;新增密码保护&quot;,
        ///      &quot;新增版本转换(不必要时不推荐进行转换)&quot;,
        ///      &quot;新增替换贴图时对JPG,BMP等格式的支持&quot;
        ///    ]
        ///  },
        ///  {
        ///    &quot;Version&quot;: &quot;1.1.0.0&quot;,
        ///    &quot;Time&quot;: &quot;2017年5月16日20:01:00&quot;,
        ///    &quot;Info&quot;: [
        ///      &quot;修复载入文件夹卡死的bug&quot;,
        ///      &quot;新增Ver5提取支持&quot;,
        ///      &quot;新增 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///
        ///  &quot;MainColor&quot;: &quot;180,214,221&quot;,
        ///
        ///  &quot;MainImage&quot;: &quot;&quot;,
        ///
        ///  &quot;MainSize&quot;: &quot;1368,768&quot;,
        ///
        ///  &quot;MainImageLayout&quot;: &quot;&quot;,
        ///
        ///  &quot;MainIcon&quot;: &quot;&quot;,
        ///
        ///  &quot;FormImage&quot;: &quot;&quot;,
        ///
        ///  &quot;FormColor&quot;: &quot;&quot;,
        ///
        ///  &quot;FormImageLayout&quot;: &quot;&quot;,
        ///
        ///  &quot;FormIcon&quot;: &quot;aww.ico&quot;,
        ///
        ///  &quot;CanvasColor&quot;: &quot;&quot;,
        ///
        ///  &quot;CanvasImage&quot;: &quot;&quot;,
        ///
        ///  &quot;CanvasSize&quot;: &quot;800,600&quot;,
        ///
        ///  &quot;StartPosition&quot;: &quot;center&quot;,
        ///
        ///  &quot;Title&quot;: &quot;&quot;
        ///} 的本地化字符串。
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
