//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtractorSharp.UnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtractorSharp.UnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;Name&quot;: &quot;default&quot;,
        ///  &quot;Rules&quot;: {
        ///    &quot;arma&quot;: 2150,
        ///    &quot;armb&quot;: 650,
        ///    &quot;armc&quot;: 2790,
        ///    &quot;armsa&quot;: 2150,
        ///    &quot;armsb&quot;: 650,
        ///    &quot;armsc&quot;: 2790,
        ///    &quot;armsx&quot;: 1350,
        ///    &quot;armx&quot;: 1350,
        ///    &quot;autoa&quot;: 2150,
        ///    &quot;autob&quot;: 650,
        ///    &quot;autoc&quot;: 2790,
        ///    &quot;axea&quot;: 2150,
        ///    &quot;axec&quot;: 2600,
        ///    &quot;axed&quot;: 200,
        ///    &quot;axex&quot;: 1350,
        ///    &quot;beamspeara&quot;: 2150,
        ///    &quot;beamspearb&quot;: 650, //?
        ///    &quot;beamspearc&quot;: 2790,
        ///    &quot;beamspeare&quot;: 2880,
        ///    &quot;beamspearx&quot;: 1350,
        ///    &quot;beamswda&quot;: 2150, //?
        ///    &quot;beamswdb&quot;: 650, //?
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string queues {
            get {
                return ResourceManager.GetString("queues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;swordman&quot;: {
        ///    &quot;hasAt&quot;: true,
        ///    &quot;weapon&quot;: [
        ///      &quot;katana&quot;,
        ///      &quot;lkatana&quot;,
        ///      &quot;sswd&quot;,
        ///      &quot;lswd&quot;,
        ///      &quot;lswd_teen&quot;,
        ///      &quot;lgswd&quot;,
        ///      &quot;mswd&quot;,
        ///      &quot;club&quot;,
        ///      &quot;gemswd&quot;,
        ///      &quot;beamswd&quot;,
        ///      &quot;boneswd&quot;
        ///    ]
        ///  },
        ///  &quot;fighter&quot;: {
        ///    &quot;hasAt&quot;: true,
        ///    &quot;weapon&quot;: [
        ///      &quot;arm&quot;,
        ///      &quot;tonfa&quot;,
        ///      &quot;lkatana&quot;,
        ///      &quot;glove&quot;,
        ///      &quot;knuckle&quot;,
        ///      &quot;claw&quot;,
        ///      &quot;gauntlet&quot;,
        ///      &quot;boneglove&quot;,
        ///      &quot;boneclaw&quot;
        ///    ]
        ///  },
        ///  &quot;gunner&quot;: {
        ///    &quot;hasAt&quot;: true,
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string weapon {
            get {
                return ResourceManager.GetString("weapon", resourceCulture);
            }
        }
    }
}
