//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtractorSharp.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtractorSharp.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;Name&quot;: &quot;中文(简体)&quot;,
        ///  &quot;LCID&quot;: 2052,
        ///  &quot;Group&quot;: {
        ///    &quot;Dictionary&quot;: {
        ///      &quot;About&quot;: &quot;关于&quot;,
        ///      &quot;AbsolutePosition&quot;: &quot;绝对坐标&quot;,
        ///      &quot;Action&quot;: &quot;动作&quot;,
        ///      &quot;ActionPause&quot;: &quot;动作记录已暂停!&quot;,
        ///      &quot;ActionRecord&quot;: &quot;动作记录已开始!&quot;,
        ///      &quot;ActionRun&quot;: &quot;动作执行已完成&quot;,
        ///      &quot;ActionTips&quot;: &quot;是否对所有贴图执行此处理？&quot;,
        ///      &quot;Add&quot;: &quot;添加&quot;,
        ///      &quot;AddAction&quot;: &quot;加入动作&quot;,
        ///      &quot;AddCompareLayer&quot;: &quot;加入对比图层&quot;,
        ///      &quot;AddFile&quot;: &quot;添加文件&quot;,
        ///      &quot;AddLayer&quot;: &quot;加入图层&quot;,
        ///      &quot;AddList&quot;: &quot;加入列表&quot;,
        ///      &quot;AddListHideImage&quot;: &quot;隐藏文件贴图&quot;,
        ///      &quot;AddMerge&quot;:  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;AddFileNoTips&quot;: false,
        ///  &quot;Animation&quot;: false,
        ///  &quot;AnimationSpeed&quot;: 20,
        ///  &quot;ApiHost&quot;: &quot;http://localhost&quot;,
        ///  &quot;AutoCheckUpdate&quot;: true,
        ///  &quot;AutoSave&quot;: false,
        ///  &quot;AutoSort&quot;: true,
        ///  &quot;CanvasImageSize&quot;: &quot;800,600&quot;,
        ///  &quot;CanvasScale&quot;: 100,
        ///  &quot;ClassifySeparator&quot;: &quot;�ָ���&quot;,
        ///  &quot;FeedbackUrl&quot;: &quot;/project/feedback/post&quot;,
        ///  &quot;FlashSpeed&quot;: 20,
        ///  &quot;GamePath&quot;: &quot;&quot;,
        ///  &quot;GifDelay&quot;: 75,
        ///  &quot;GifTransparent&quot;: &quot;0,0,0,0&quot;,
        ///  &quot;GridGap&quot;: 100,
        ///  &quot;LayerMaximum&quot;: 20,
        ///  &quot;LCID&quot;: 2052,
        ///  &quot;LinearDodge&quot;: false,
        ///  &quot;LinearDodgeSpriteC [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;arma&quot;: 2150,
        ///    &quot;armb&quot;: 650,
        ///    &quot;armc&quot;: 2790,
        ///    &quot;armsa&quot;: 2150,
        ///    &quot;armsb&quot;: 650,
        ///    &quot;armsc&quot;: 2790,
        ///    &quot;armsx&quot;: 1350,
        ///    &quot;armx&quot;: 1350,
        ///    &quot;autoa&quot;: 2150,
        ///    &quot;autob&quot;: 650,
        ///    &quot;autoc&quot;: 2790,
        ///    &quot;axea&quot;: 2150,
        ///    &quot;axec&quot;: 2600,
        ///    &quot;axed&quot;: 200,
        ///    &quot;axex&quot;: 1350,
        ///    &quot;beamspeara&quot;: 2150,
        ///    &quot;beamspearb&quot;: 650, //?
        ///    &quot;beamspearc&quot;: 2790,
        ///    &quot;beamspeare&quot;: 2880,
        ///    &quot;beamspearx&quot;: 1350,
        ///    &quot;beamswda&quot;: 2150, //?
        ///    &quot;beamswdb&quot;: 650, //?
        ///    &quot;beamswdc&quot;: 2790,
        ///    &quot;beamswdx&quot;: 1 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;MainColor&quot;: &quot;180,214,221&quot;,
        ///
        ///  &quot;MainImage&quot;: &quot;&quot;,
        ///
        ///  &quot;MainSize&quot;: &quot;1368,768&quot;,
        ///
        ///  &quot;MainImageLayout&quot;: &quot;&quot;,
        ///
        ///  &quot;MainIcon&quot;: &quot;&quot;,
        ///
        ///  &quot;FormImage&quot;: &quot;&quot;,
        ///
        ///  &quot;FormColor&quot;: &quot;&quot;,
        ///
        ///  &quot;FormImageLayout&quot;: &quot;&quot;,
        ///
        ///  &quot;FormIcon&quot;: &quot;aww.ico&quot;,
        ///
        ///  &quot;CanvasColor&quot;: &quot;&quot;,
        ///
        ///  &quot;CanvasImage&quot;: &quot;&quot;,
        ///
        ///  &quot;CanvasSize&quot;: &quot;840,600&quot;,
        ///
        ///  &quot;StartPosition&quot;: &quot;center&quot;,
        ///
        ///  &quot;Title&quot;: &quot;&quot;
        ///} 的本地化字符串。
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
