//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtractorSharp.DressingTools.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtractorSharp.DressingTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;name&quot;: &quot;swordman&quot;,
        ///        &quot;frame&quot;: 176,
        ///        &quot;transfer&quot;: {
        ///            &quot;weaponmaster&quot;: &quot;swordman?hair=12800&amp;cap=13000&amp;face=11900&amp;neck=11700&amp;coat=14300&amp;skin=0000&amp;belt=10400&amp;pants=13400&amp;shoes=12600&quot;,
        ///            &quot;berserker&quot;: &quot;swordman?hair=13000&amp;cap=13200&amp;face=12100&amp;neck=12000&amp;coat=14500&amp;skin=0000&amp;belt=10700&amp;pants=13600&amp;shoes=12800&quot;,
        ///            &quot;asura&quot;: &quot;swordman?hair=12600&amp;cap=12800&amp;face=11700&amp;neck=11500&amp;coat=14100&amp;skin=0000&amp;belt=10200&amp;pants=13200&amp;shoes=12400&quot;,
        ///            &quot;soul [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string profession {
            get {
                return ResourceManager.GetString("profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;Name&quot;: &quot;default&quot;,
        ///  &quot;Rules&quot;: {
        ///    &quot;arma&quot;: 2150,
        ///    &quot;armb&quot;: 650,
        ///    &quot;armc&quot;: 2790,
        ///    &quot;armsa&quot;: 2150,
        ///    &quot;armsb&quot;: 650,
        ///    &quot;armsc&quot;: 2790,
        ///    &quot;armsx&quot;: 1350,
        ///    &quot;armx&quot;: 1350,
        ///    &quot;autoa&quot;: 2150,
        ///    &quot;autob&quot;: 650,
        ///    &quot;autoc&quot;: 2790,
        ///    &quot;axea&quot;: 2150,
        ///    &quot;axec&quot;: 2600,
        ///    &quot;axed&quot;: 200,
        ///    &quot;axex&quot;: 1350,
        ///    &quot;beamspeara&quot;: 2150,
        ///    &quot;beamspearb&quot;: 650, //?
        ///    &quot;beamspearc&quot;: 2790,
        ///    &quot;beamspeare&quot;: 2880,
        ///    &quot;beamspearx&quot;: 1350,
        ///    &quot;beamswda&quot;: 2150, //?
        ///    &quot;beamswdb&quot;: 650, //?
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string queues {
            get {
                return ResourceManager.GetString("queues", resourceCulture);
            }
        }
    }
}
